# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adventist Idenity Guideline System
email: hardingeb@gc.adventist.org
description: > # this means to ignore newlines until "baseurl:"
  The Identity Guideline System helps the Adventist Church unite our
  spoken, published, and produced materials to present a unified
  identity of logo & branding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: adventistchurch
# github_username:  bradfrost

# Build settings
highlighter: highlighter
markdown: kramdown
exclude: [node_modules, ‘css’, ‘_scss’]
keep_files: ['_site/css']

plugins:
  - jekyll-last-modified-at
