# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adventist Idenity Guideline System
email: hardingeb@gc.adventist.org
description: > # this means to ignore newlines until "baseurl:"
  The Identity Guideline System helps the Adventist Church unite our
  spoken, published, and produced materials to present a unified
  identity of logo & branding.
footer_desc:
  identity.adventist.org is the official Identity Guidelines website of the Seventh-day Adventist world church
global_desc:
  Seventh-day Adventists are devoted to helping people understand the Bible to find freedom, healing and hope.


sites:
  -
    title: Adventist.org
    url: https://www.adventist.org
  -
    title: North American Division of Seventh-day Adventists
    url: https://www.nadadventist.org

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: adventistchurch
github_username:  adventistchurch


# ALPS Theme Color Options
#
## Bright
# Treefrog:   u-theme--treefrog
# Ming:       u-theme--ming
# Bluejay:    u-theme--bluejay
# Iris:       u-theme--iris
# Lily:       u-theme--lily
# Scarlett:   u-theme--scarlett
# Campfire:   u-theme--campfire
# Winter:     u-theme--winter
#
## Muted
# Forest:     u-theme--forest
# Cave:       u-theme--cave
# Denim:      u-theme--denim
# Emperor:    u-theme--emperor
# Grapevine:  u-theme--grapevine
# Velvet:     u-theme--velvet
# Earth:      u-theme--earth
# Night:      u-theme--night

html_classes: u-theme--campfire

body_classes: has-grid

# Build settings
highlighter: rouge
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-last-modified-at

